# Use an OpenJDK image as the base image
FROM openjdk:17

# Set the working directory inside the container
WORKDIR /app

# Copy the Java source code and compile it
COPY entrypoint.java /app
RUN javac entrypoint.java

# Set the entrypoint to run the compiled Java application
ENTRYPOINT ["java", "entrypoint"]
